# frontend/render.yaml
services:
  - type: static
    name: nexora-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html