services:
  - type: web
    name: nexora-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://nexora-website-epts.onrender.com